# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'ajeje' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ajeje
  pod 'MDCSwipeToChoose'
  pod 'Sugar'
  pod 'EZSwiftExtensions', :git => 'https://github.com/goktugyil/EZSwiftExtensions.git', :branch => 'Swift2.3' #For Swift 2.3


  target 'ajejeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ajejeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
